### ISSUE TITLE
CORS not work in browser

### ISSUE THREAD

**Issue by njzydark** [flatz/ps4_remote_pkg_installer#10]
## Problem

When send `POST` request from browser, the`OPTIONS` request will send first as the preflighted request https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests, and the CORS is happen, because the server only set `Access-Control-Allow-Origin` in https://github.com/flatz/ps4_remote_pkg_installer/blob/master/server.c#L1493

## Solution

```
sb_send_header(s, "Access-Control-Allow-Origin", "*");
sb_send_header(s, "Access-Control-Allow-Headers", "*");
sb_send_header(s, "Access-Control-Allow-Methods", "*");
```

Because I can't build this project by myself without SDK（I try use [OpenOrbis-PS4-Toolchain](https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain), because I'm not very familiar with c language, I can't finish the related adjustment ）, Can you provide the download address of the SDK?

**Comment by saeedmou** [comment]
Use this:
This is a OOSDK port of flat's ps4_remote_pkg_installer, all credit goes to them and their amazing work!
https://github.com/Backporter/ps4_remote_pkg_installer-OOSDK

**Comment by njzydark** [comment]
> Use this: This is a OOSDK port of flat's ps4_remote_pkg_installer, all credit goes to them and their amazing work! https://github.com/Backporter/ps4_remote_pkg_installer-OOSDK

I've tried it, it doesn't compile successfully on macOS, there are many errors

**Comment by njzydark** [comment]
I have fixed this issue https://github.com/njzydark/ps4_remote_pkg_installer-OOSDK
