### ISSUE TITLE
Hex number in JSON

### ISSUE THREAD

**Issue by digglife** [flatz/ps4_remote_pkg_installer#8]
First of all, thanks very much for the great tool! It's really convenient to install pkgs with Remote Package Installer.

I'm trying to write a client recently and I found that the JSON body returned by the server contains hex number like `0x80990019`, which is not a valid number type in JSON specification. So by default, it's not parsable by command line like `jq` or standard library of Golang or Python etc. Could I ask if there is any particular reason for using raw hex number instead of float? 

Thank you!

**Comment by flatz** [comment]
Hi.
There was no reason to use raw hex number, it's me who forgot to add quotes around it. It's no longer maintained, so you can fix it by yourself. :)
Thanks anyway!

**Comment by digglife** [comment]
@flatz Understood. Thank you for replying!

**Comment by Gkiokan** [comment]
@digglife Just parse it as JSON5 and you are fine.
